services:
  - type: web
    name: wordle-score
    env: node
    buildCommand: npm install && npm run build && npx tailwindcss -i ./public/css/input.css -o ./public/css/output.css --minify
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

